### ISSUE TITLE
Enter key does not work to jump to tests, test results, or code coverage results

### ISSUE THREAD

**Issue by NeilJustice** [axodox/AxoCover#121]
The Enter key and numpad Enter key do not work to jump to tests, test results, or code coverage results. In order to open these items from the AxoCover window, a programmer currently has to context switch away from the keyboard-focused zone of productivity, grab the mouse, double click, release the mouse, then context switch back to the keyboard.

Tests:

![image](https://user-images.githubusercontent.com/1912242/30550516-46e018c4-9c5d-11e7-9e88-9cdee9e67aba.png)

Test results:

![image](https://user-images.githubusercontent.com/1912242/30550523-4b940ba0-9c5d-11e7-9eec-99589fb7dc5f.png)

Code coverage results:

![image](https://user-images.githubusercontent.com/1912242/30550527-4e2edf5c-9c5d-11e7-9eca-b1c39582e89f.png)

**Comment by axodox** [comment]
On master.

**Comment by axodox** [comment]
Released.
