### ISSUE TITLE
AxoCover explorer sometimes does not reset when Debugging tests.

### ISSUE THREAD

**Issue by JakenVeina** [axodox/AxoCover#130]
I find that sometimes when I'm breakpoint-debugging a test, and I realize my mistake and click the "Stop" button in Visual Studio, the AxoCover window doesn't recognize that debugging has stopped, and indefinitely waits for execution to complete with a status of "Finalizing Operation" or similar. This is particularly cumbersome, as the VS editor itself doesn't respond normally to input when this happens (it still think's something's running, and doesn't allow file editing, and other normal actions). The AxoCover "Abort" button doesn't help. The only way I've found to resolve the issue is to completely restart VS.

I'm fairly sure this doesn't happen every time I try and exit debugging in such a manner, but I haven't been able to find a pattern to it.

Is there any extra information I can collect for you when this occurs, that might help?

**Comment by axodox** [comment]
Simplest would be to have a [memory dump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) (a minidump so it is not so large) so I can check what the threads were doing.

However a memory dump can potentially expose some sensitive information (local variable values and the like), so if you can attach another VS to the hanging one, break the execution, and look at parallel stacks and send the AxoCover related stack-traces from there, that would help too.

**Comment by axodox** [comment]
Released fix.
