### ISSUE TITLE
AxoTools - AxoCover

### ISSUE THREAD

**Issue by 304NotModified** [axodox/AxoCover#132]
Maybe I'm missing something,

but why isn't this repository called AxoCover? It's a bit hard to find now.

**Comment by axodox** [comment]
I plan to have more extensions reusing the same code (control styles, some base classes etc.), and I thought it would be easier to manage if it is in one repository - at least if only I work on it. So I named it like that.

**Comment by axodox** [comment]
Still I might rename it for now since it will take time to get there...

**Comment by 304NotModified** [comment]
AFAIK if you rename it, Github will create a redirect.

I would recommend to rename it for now, it makes it easier to find. New stuff could be also addin in another repo.

**Comment by axodox** [comment]
Rename done.

**Comment by 304NotModified** [comment]
👍 redirection also works :)
