### ISSUE TITLE
Feature request: A keyboard shortcut assignable command for toggling code coverage coloring on and off

### ISSUE THREAD

**Issue by NeilJustice** [axodox/AxoCover#135]
A command that is keyboard shortcut assignable for toggling on and off code coverage coloring would be appreciated.

**Comment by axodox** [comment]
I see, one way would be to define a VS command for this, which then can have a keyboard shortcut assigned (and can be also added to toolbars, menus etc.).

**Comment by axodox** [comment]
Added it to master, see Tools / Show Coverage command. Note this toggles all AxoCover adornments, and it is enabled by default. I decided to not save this, so coverage is always displayed if it is not disabled manually after a restart. (As the adornments can be permanently turned off in settings already.)

**Comment by axodox** [comment]
Released.
