### ISSUE TITLE
"Debugger failed to attach." in the AxoCover output window despite the debugger attaching

### ISSUE THREAD

**Issue by NeilJustice** [axodox/AxoCover#136]
I'm seeing "Debugger failed to attach." in the AxoCover output window despite the debugger attaching.

![image](https://user-images.githubusercontent.com/1912242/32417073-53d71d52-c219-11e7-8cea-eb8dbcb52e6a.png)

**Comment by axodox** [comment]
I suggest increasing debugger timeout here:
![image](https://user-images.githubusercontent.com/22882208/32688089-b7b34a5c-c6ca-11e7-8874-38a7fcaa226b.png)

**Comment by NeilJustice** [comment]
From reading the source code it appears the IOptions.DebuggerTimeout property is in seconds yet this value is passed to ManualResetEvent.WaitOne() which expects milliseconds:

![image](https://user-images.githubusercontent.com/1912242/32703193-de5468b0-c7b7-11e7-8754-639349fea592.png)

**Comment by axodox** [comment]
You are right, I will push an update in 10 min.

**Comment by axodox** [comment]
Release done.
