### ISSUE TITLE
Feature request: Ability to configure AxoCover settings without first having to open and build a solution

### ISSUE THREAD

**Issue by NeilJustice** [axodox/AxoCover#137]
It would be nice to be able to configure AxoCover settings without first having to open and build a solution.

Current behavior:

![image](https://user-images.githubusercontent.com/1912242/32417395-b03fc012-c21e-11e7-8f11-8d26016a13cb.png)

**Comment by axodox** [comment]
Pushed this on master: you can now access the settings tab without opening a solution. I set the settings to only show the about / feedback and update settings as the other settings do not have any effect without a solution.

**Comment by axodox** [comment]
Released.
