### ISSUE TITLE
Feature Request - Axocover currently doesnt take out coverage for library type or web based projects

### ISSUE THREAD

**Issue by mkbansal145** [axodox/AxoCover#140]
hi,
great tool, really liked its utility and report structure.
But my project is Web based and Library project. I tried but Axocover doesn't understand the Nunit project in my web project.
Am I missing anything or is this feature yet to come.

**Comment by axodox** [comment]
Are the projects using full .Net Framework, or .Net core (which is not supported)?

**Comment by mkbansal145** [comment]
The project is using full.net framework

**Comment by axodox** [comment]
Could you please create a small repro project which demonstrates the issue and upload as a zip file here?

**Comment by mkbansal145** [comment]
Hi
The issue was with the mocking framework profiler. The issue is fixed
Apologies for the late reply.
Thanks
Mayank
