### ISSUE TITLE
Default execution path is not output directory?

### ISSUE THREAD

**Issue by VanKurt** [axodox/AxoCover#142]
When running my unit tests e.g. via ReSharper, the default execution path/working directory is:

> "D:\\Projects\\MyProject\\MyProject.UnitTests\\bin\\x86\\Debug"

This is the output directory of my test project, and thus everything works fine.

But when running the tests via AxoCover, the directory is different:

> "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\IDE"

This leads to several problems: the assembly references are not found, since the assemblies are copied to the project's output directory. Also the required test data files (which are also located in the output directory) are not found as well.

Is there a reason why AxoCover chooses a working directory different from my test project's output folder?
Can I change that somehow?

**Comment by axodox** [comment]
No there is no reason, I think this is a bug. Seems weird since I would expected this would have been encountered after a year of the first release. Can you tell me what test framework you use? (might be specific to one)

As a workaround you could add an AssemblyInitializer (in MSTEST or similar alternative in other frameworks) to set the working directory manually.

**Comment by VanKurt** [comment]
Thanks for the quick feedback. Here are the tools I use:

- Visual Studio 2013 Professional Update 5
- NUnit 3.9
- AxoCover 1.1.4.8

I use the following code to query the current working directory:

`var path = System.IO.Directory.GetCurrentDirectory();`

PS: This project is really awesome. Good job! :-)

**Comment by axodox** [comment]
Thanks, I planned to spend a day or two of my vacation on AxoCover, before returning to work. I will definitely put this on my list to do.

By the way, I figured out a reason I would not run into this issue myself:
I always avoid using working directory to locate dependencies - as working directory can be easily messed up (e.g. by calling scripts, or other modules of the application), instead I use the assembly directory, application base or equivalent. For example:
Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location)
(This might or might not make sense in your case.)

**Comment by axodox** [comment]
A little later than planned, but it is done and released now.
