### ISSUE TITLE
"Scanning solution for test" and then "Done" quickly.It doesn`t work already.

### ISSUE THREAD

**Issue by 3xCode** [axodox/AxoCover#144]
AxoCover 1.1.4.8 with vs2013, I use nunit as my unit test framework,when I run unit test,the AxoCover shows "build"->"Scanning solution for test"->"Done",but it shows nothing,the Report Tab still shows"Cover tests to get a coverage report".the settings are default.

**Comment by 3xCode** [comment]
the Tests tab shows axocover found no unit tests in this solution.But my solution have a Nunit Test project..

**Comment by 3xCode** [comment]
OK,i know why this happen...my os is 64,and the axocover can choose x86 or 64 in its setting,but the 64 seems not work.when i choose x86,it can work correctly.

**Comment by axodox** [comment]
It actually does work, but only if all your code is also x64 compatible, as 64bit process cannot load 32bit binaries. I plan to add a detector for x86 / x64 tests in the future, so this will be selected automatically in most cases, also I will show a banner to select it otherwise.

**Comment by 3xCode** [comment]
thanks for your reply.

Best Wishes!



372845269@qq.com
 
From: Péter Major
Date: 2018-01-16 15:30
To: axodox/AxoCover
CC: 3xCode; State change
Subject: Re: [axodox/AxoCover] "Scanning solution for test" and then "Done" quickly.It doesn`t work already. (#144)
It actually does work, but only if all your code is also x64 compatible, as 64bit process cannot load 32bit binaries. I plan to add a detector for x86 / x64 tests in the future, so this will be selected automatically in most cases, also I will show a banner to select it otherwise.
