### ISSUE TITLE
Nothing happend when test finished

### ISSUE THREAD

**Issue by Zefek** [axodox/AxoCover#147]
When test is finished there is not green flag test passed. When there is error it is ok, red flag is shown. When I want to test test group (by namespace) it is stopped when first test is finished.

**Comment by axodox** [comment]
Maybe it is crashing at the end, can you check in the event viewer / application log, if .Net crash events related to AxoCover.Runner are logged?

**Comment by Zefek** [comment]
There is nothing in event viewer about axocover.

**Comment by axodox** [comment]
Is the DLL copied to the target directory? Can you create me a sample project?

**Comment by Zefek** [comment]
Problem was in log4net library, not axo cover extension. Thank you for your help :)
