### ISSUE TITLE
Test doesn't finish

### ISSUE THREAD

**Issue by VitoHanoi** [axodox/AxoCover#148]
Hello there,

I'm new using this tool. I have Axo (release) last version and VS2017. 
I am developing a selenium test project (Web Driver). And my test has passed (even on debug mode, i'm hitting the last line with success) but Axo is trying to "Finish the operation" by "shutting down..." and exiting something... but it is blocked at this step and I have to Abort the test to do something. Same Thing With Cover Tests option..

![shutting](https://user-images.githubusercontent.com/16385289/35938566-5f96a7cc-0cae-11e8-86a5-cc4936c3054d.png)

![image](https://user-images.githubusercontent.com/16385289/35939215-55b70308-0cb0-11e8-906a-cceca7f8d424.png)

![image](https://user-images.githubusercontent.com/16385289/35939348-b838b6de-0cb0-11e8-8862-60c2ceb17433.png)

I can see that the "Console" is still running on background

![str](https://user-images.githubusercontent.com/16385289/35939745-f4b5a328-0cb1-11e8-960f-560ed9f769d9.png)

It doesn't happen when I'm trying a simple test like Assert.IsTue(true);
Do you have any idea of what could be the issue? I'm supposing Selenium but my tests are running well on MSTest or Resharper sessions. 

And just a question apart, Is it possible to cover ordered test (MSTest v1),  as my Selenium project has to be run as ordered tests... 
Thanks in advance.

Guillaume

**Comment by axodox** [comment]
Usage with Selenium is something I had not tried before. Can you please create me a small sample project and attach it to the issue?

About ordered tests: this feature is not supported, though it would not be that complex to implement.

**Comment by VitoHanoi** [comment]
[SeleniumProject.zip](https://github.com/axodox/AxoCover/files/1717747/SeleniumProject.zip)

Here is the project. really simple.
Framework to drive a browser.
one Test file to test it.
I added a Ordered file so you could test of implement this feature.
Same behavior as my project (finishing operation)

Thanks in advance

**Comment by axodox** [comment]
And... it is a deadlock. I added a fix on master: https://github.com/axodox/AxoCover/releases/tag/master-1.1.317.

For the ordered tests I was wondering if adding an option to execute tests in declaration order would make more sense, since that way you could avoid creating these ordered test files. In this case you would have to define your tests in order in your test class, then execution would follow that order.

What do you think?

**Comment by VitoHanoi** [comment]
Hey,
Thank you for your answer. I will test it after its release.

Regarding the ordered tests. Sure just an option to execute tests in declaration order would be fine. but how will it behave if I have 1 test per file (multiple files), and several test classes? it would be dependent of the building I suppose?
It is such a shame that MSTest doesn't have an OrderAttribute like NUnit...
Thanks

**Comment by axodox** [comment]
I would leave that to the order of the test discovery. I would probably offer 4 options for ordering:
- Default (leave to the test framework - this is usually alphabetical)
- Alphabetical
- Declaration
- Randomized (different for each run)
However overriding the order could decrease performance though, as I would need to call the executor per test (as to avoid it reordering the tests). I will need to test how significant this could be. I could also add test framework specific order control, but that is more work.

I could also possibly create an AxoCover specific test library, with some helper attributes, which could control the test execution order or define my own ordered test format etc. - I would like to avoid adding an MSTEST only feature. However I would rather have the existing libraries cover this scenario instead. Alternatively I could create a command line capable universal test runner from the AxoCover.Runner.

My future plan is to switch over to Microsoft's new test framework, which is .Net Core capable, but for that I first need to get my AxoCover specific changes back into the respective xUnit, NUnit libraries and then implement plug-ins for the MS's runner, which is a lot of work. And I am concerned with the stability of the APIs offered by it. I might delay this test runner switch until I will have a personal need for .Net Core.

**Comment by axodox** [comment]
I created a new issue for ordering the tests, and closed this
