### ISSUE TITLE
Automatic build when running tests

### ISSUE THREAD

**Issue by shabtaisharon** [axodox/AxoCover#149]
Currently, i have to build the solution and then run the tests, and I need to do that after every change.
It would be helpful if you could add a setting for automatic build when running tests.

**Comment by axodox** [comment]
That is a valid request. Although AxoCover already has the reverse of that: run tests after each build. That you can do by selecting a node in the tree of tests and then selecting cover after build:
![image](https://user-images.githubusercontent.com/22882208/36062581-bad10ade-0e6f-11e8-8de3-867b07d0d33d.png)
This way you need no repeated work after each change, just do Ctrl+Shift+B etc. to build and run tests.

**Comment by axodox** [comment]
Added auto-build on latest master, will release it next week.

**Comment by shabtaisharon** [comment]
Thank you very  much :+1:

**Comment by axodox** [comment]
Released.
