### ISSUE TITLE
feature request: option - flatten tree for project root namespace

### ISSUE THREAD

**Issue by mcdon-ron** [axodox/AxoCover#150]
The team likes project names that contain multiple periods '.'. This results in a default namespace containing periods, and a bunch of nested hierarchy in the test runner before getting to the actual tests.

Could an option be added to collapse the hierarchy of the project's root namespace to a single node? Maybe collapsing single nodes of hierarchy would be easier, because code could use something other than the project's default namespace.

like:

- Marklar
    - Durka
        - Tests

becomes:

    Marklar.Durka.Tests

**Comment by axodox** [comment]
Put it in master: https://github.com/axodox/AxoCover/releases/tag/master-1.1.313
Will release after some testing.

**Comment by axodox** [comment]
Released.
