### ISSUE TITLE
Adjust/Clear line coverage visualization

### ISSUE THREAD

**Issue by bmgandre** [axodox/AxoCover#151]
After running code coverage and starting editing, if new lines are added/removed/moved, the visualization marks stays fixed. This leads to confusion sometimes.
One approach would be add an option to clear visualization marks on editing.
Other approach would be move the visualization marks on editing.

**Comment by axodox** [comment]
It is coming: https://github.com/axodox/AxoCover/tree/feature/lineMapping

**Comment by axodox** [comment]
It is on master now, you can download it from releases. I will publish after some testing next week.

**Comment by bmgandre** [comment]
Great job @axodox!

I've tested version 1.1.6.6. The only issue saw until now is that if `Build project automatically` is checked, the project builds but the test do not start.

**Comment by axodox** [comment]
OK, I see some error in the telemetry which could cause that, I will look into it.

**Comment by axodox** [comment]
Released
