### ISSUE TITLE
How to Specify Modules for exclusion from Code coverage

### ISSUE THREAD

**Issue by mkbansal145** [axodox/AxoCover#154]
How and where can I specify the modules to be excluded from code coverage
I would like to exclude all dlls having "_test" in their name.

Your help is much appreciated.
Thanks
Mayank

**Comment by axodox** [comment]
You can exclude test assemblies like this:
![image](https://user-images.githubusercontent.com/22882208/37205143-f157dbe4-2393-11e8-8039-78f10e2acf6a.png)

**Comment by mkbansal145** [comment]
this totally solved the issue
Thanks :)
