### ISSUE TITLE
Add sort options in report tab

### ISSUE THREAD

**Issue by eylvisaker** [axodox/AxoCover#155]
It would be really nice to be able to sort the list of items in the treeview on the reports tab so that at each level of the tree, within that object the methods/namespaces/classes which have the most uncovered lines would appear at the top.

**Comment by axodox** [comment]
Added it on latest master build: https://github.com/axodox/AxoCover/releases
Will release with some other changes after testing.

**Comment by axodox** [comment]
Released.
