### ISSUE TITLE
Axo coverage not removed when deselected

### ISSUE THREAD

**Issue by jcurl** [axodox/AxoCover#157]
*Environment*: Visual Studio 2015 Enterprise Edition, with NUnit 2.6.4 test cases, testing a class assembly in .NET 4.0. Build mode is "Debug" for the class under test.

*Steps to Reproduce*:
* Enable the option: Tools -> Show Coverage
* Run AxoCover and you should see the red/orange/darkgreen/green bars in the IDE for the code being seen
* Disable the option: Tools -> Show Coverage

*Observed Behaviour*:
* For the current screen, the bars indicating coverage goes away, but then scroll up and down and the bars come back.
* Open a new file, expect there to be no coverage shown,  but it is

Rerunning AxoCover with the option disabled doesn't help.

**Comment by axodox** [comment]
Fix released
