### ISSUE TITLE
Support of latest (or at least 3.9) NUnit test framework

### ISSUE THREAD

**Issue by Ciget** [axodox/AxoCover#165]
Hi,

thanks a lot for an amazing tool. I would like to ask for support of latest version of NUnit.

Thanks a lot.

**Comment by axodox** [comment]
Sorry I have a lot of things going on, and have no time for AxoCover development as of now.

However if you are willing to do it yourself I can provide information on how to make it work. I estimate it would take around 6-12h work to provide this support (depending on your experience). - Which is not so much work time, but it is a lot of free-time, especially if you do not have any besides the weekend and have a lot of requests...

**Comment by Ciget** [comment]
I dont know what`s happened, but now (latest version of Axo) is working with NUnit 3.9.

Thanks, if u dont mind - pls close the request.
