### ISSUE TITLE
Code Coverage report generation failure

### ISSUE THREAD

**Issue by RoyC-Retail-Assist** [axodox/AxoCover#183]
AxoCover has been working brilliantly for me up until now.

When running code coverage the tests all run but the coverage report fails to generate.  

The following is logged (with debug setting enabled):

> < Test execution finished.
> Shutting down...
> Exiting...
>    SerializableException: Cannot access a disposed object.
>    Object name: 'System.Net.Sockets.Socket'.
>       at System.Net.Sockets.Socket.EndAccept(IAsyncResult asyncResult)
> Generating coverage report...
>    SerializableException: The operation cannot be completed because the pipe was closed.  This may have been caused by the application on the other end of the pipe exiting.
>       at System.ServiceModel.Channels.PipeConnection.OnAsyncReadComplete(Boolean haveResult, Int32 error, Int32 numBytes)
>    
>    SerializableException: The operation cannot be completed because the pipe was closed.  This may have been caused by the application on the other end of the pipe exiting.
>    SerializableException: The operation cannot be completed because the pipe was closed.  This may have been caused by the application on the other end of the pipe exiting.
>       at System.ServiceModel.Channels.PipeConnection.EndRead()
>    
>    SerializableException: The operation cannot be completed because the pipe was closed.  This may have been caused by the application on the other end of the pipe exiting.
> Committing...
> No results, this could be for a number of reasons. The most common reasons are:
>     1) missing PDBs for the assemblies that match the filter please review the
>     output file and refer to the Usage guide (Usage.rtf) about filters.
>     2) the profiler may not be registered correctly, please refer to the Usage
>     guide and the -register switch.
> Test execution finished.
> 

I've tried switching from TCP to Named Pipes but get a similar issue for both.

I would try the -register switch as suggested but I cannot find the Usage.rtf in the AxoCover source code that might help me in doing this.

I've updated to VS 15.8.8 today so wonder if that could have any bearing on this.

**Comment by axodox** [comment]
Register as shown here: https://github.com/axodox/AxoCover/issues/172

**Comment by RoyC-Retail-Assist** [comment]
Thanks and apologies I should have looked for existing issues before raising another one.
